// frontend/src/lib/components/layout/analysis-panel.svelte
<script lang="ts">
	import {
		Info,
		CheckCircle,
		Clock,
		Filter,
		XCircle,
		AlertCircle,
		AlertTriangle,
		SearchCode,
		PanelRightClose
	} from 'lucide-svelte';
	import type { Severity, Vulnerability } from '$lib/types/api';
	import type { Scans } from '$lib/types/api';
	import * as Select from '$lib/components/ui/select/';
	import { Button } from '../ui/button';

	export let onVulnerabilitySelect: (vulnerability: Vulnerability) => void;
	export let onScanChange: ((scanId: string | null) => void) | undefined = undefined;
	export let onTogglePanel: (() => void) | undefined = undefined;
	export let scans: Scans[];
	export let projectId: string | null = null;
	export let currentSelectedScan: Scans | null = null;

	let selectedSeverity = 'all';
	let expandedVuln: string | null = null;
	let selectedScan: Scans | null = null;
	let selectedScanId = '';

	const severityOptions = [
		{ value: 'all', label: 'All Severities' },
		{ value: 'critical', label: 'Critical' },
		{ value: 'high', label: 'High' },
		{ value: 'medium', label: 'Medium' },
		{ value: 'low', label: 'Low' }
	];

	$: selectedSeverityLabel =
		severityOptions.find((opt) => opt.value === selectedSeverity)?.label ?? 'Select severity';
	$: selectedScanLabel = selectedScan
		? `${
				selectedScan.status === 'completed'
					? '✅'
					: selectedScan.status === 'running'
						? '🔄'
						: selectedScan.status === 'failed'
							? '❌'
							: '⏳'
			} ${
				selectedScan.finishedAt
					? new Date(selectedScan.finishedAt).toLocaleDateString() +
						' ' +
						new Date(selectedScan.finishedAt).toLocaleTimeString()
					: selectedScan.startedAt
						? new Date(selectedScan.startedAt).toLocaleDateString() +
							' ' +
							new Date(selectedScan.startedAt).toLocaleTimeString()
						: 'Unknown'
			}`
		: 'Select scan';

	// Sync with parent's selected scan
	$: if (currentSelectedScan) {
		selectedScan = currentSelectedScan;
		selectedScanId = currentSelectedScan.id;
	} else if (scans.length > 0 && !selectedScan) {
		selectedScan = scans[0];
		selectedScanId = scans[0].id;
		if (onScanChange) {
			onScanChange(scans[0].id);
		}
	}

	const handleScanSelection = (newScanId: string) => {
		console.log('AnalysisPanel: handleScanSelection called with:', newScanId);
		if (newScanId && newScanId !== selectedScanId) {
			selectedScanId = newScanId;
			const newScan = scans.find((s) => s.id === newScanId);
			if (newScan) {
				console.log('AnalysisPanel: Found scan:', { id: newScan.id, status: newScan.status });
				selectedScan = newScan;
				if (onScanChange) {
					onScanChange(newScanId);
				}
			}
		}
	};

	function handleVulnerabilityClick(vuln: Vulnerability) {
		onVulnerabilitySelect(vuln);
		expandedVuln = expandedVuln === vuln.id ? null : vuln.id;
	}

	$: filteredIssues =
		selectedScan?.issues?.filter(
			(issue) => selectedSeverity === 'all' || issue.severity.toLowerCase() === selectedSeverity
		) || [];

	$: console.log('AnalysisPanel DEBUG:', {
		selectedScanId,
		selectedScan: selectedScan
			? {
					id: selectedScan.id,
					status: selectedScan.status,
					totalIssues: selectedScan.results?.totalIssues,
					issuesLength: selectedScan.issues?.length || 0
				}
			: null,
		filteredIssuesLength: filteredIssues.length,
		selectedSeverity
	});

	$: severityStats = {
		critical: {
			title: 'Critical',
			count: selectedScan?.results?.issuesBySeverity?.critical || 0,
			color: 'text-red-600'
		},
		high: {
			title: 'High',
			count: selectedScan?.results?.issuesBySeverity?.high || 0,
			color: 'text-orange-600'
		},
		medium: {
			title: 'Medium',
			count: selectedScan?.results?.issuesBySeverity?.medium || 0,
			color: 'text-yellow-600'
		},
		low: {
			title: 'Low',
			count: selectedScan?.results?.issuesBySeverity?.low || 0,
			color: 'text-blue-600'
		}
	};
</script>

{#if scans.length === 0}
	<div class="flex h-full flex-col">
		<div class="flex items-center justify-between border-b p-4">
			<h3 class="truncate text-lg font-semibold text-gray-900 dark:text-gray-100">
				Security Analysis
			</h3>
			{#if onTogglePanel}
				<Button variant="ghost" onclick={onTogglePanel} title="Rétracter le panneau d'analyse">
					<PanelRightClose />
				</Button>
			{/if}
		</div>
		<div class="text-foreground flex flex-1 items-center justify-center">
			<div class="truncate text-center">
				<Clock class="text-muted-foreground mx-auto mb-4 h-12 w-12" />
				<p class="text-lg font-medium">No analysis available</p>
				<p class="text-muted-foreground text-sm">
					Start a scan to see security analysis results here.
				</p>
			</div>
		</div>
	</div>
{:else}
	<div class="flex h-full flex-col">
		<div class="flex items-center justify-between border-b p-4">
			<h3 class="truncate text-lg font-semibold text-gray-900 dark:text-gray-100">
				Security Analysis
			</h3>
			{#if onTogglePanel}
				<Button variant="ghost" onclick={onTogglePanel} title="Rétracter le panneau d'analyse">
					<PanelRightClose />
				</Button>
			{/if}
		</div>
		<div class="flex-shrink-0 border-b p-4">
			<div class="mb-2 grid grid-cols-2 gap-3">
				<div
					class="bg-card flex h-fit items-center justify-between rounded-lg border p-3 shadow-sm"
				>
					<p class="text-sm">Total Issues</p>
					<p class="text-xl font-bold">{selectedScan?.results?.totalIssues || 0}</p>
				</div>
				<div
					class="bg-card flex h-fit items-center justify-between rounded-lg border p-3 shadow-sm"
				>
					<p class="text-sm">Scanned Files</p>
					<p class="text-xl font-bold">{selectedScan?.results?.scannedFiles || 0}</p>
				</div>
			</div>

			<div class="mb-4 grid grid-cols-4 gap-2">
				{#each Object.entries(severityStats) as [key, { count, color, title }]}
					<button
						class="bg-card rounded-lg border p-3 text-center shadow-sm transition-colors"
						onclick={() => {
							selectedSeverity = key;
							expandedVuln = null;
						}}
					>
						<div class="text-2xl font-bold {color}">{count}</div>
						<div class="mt-1 text-xs text-gray-600 dark:text-gray-400">{title}</div>
					</button>
				{/each}
			</div>

			<div class="mb-2 flex items-center space-x-2">
				<Filter class="text-muted-foreground h-4 w-4" />
				<Select.Root type="single" bind:value={selectedSeverity}>
					<Select.Trigger class="w-[180px]">
						{selectedSeverityLabel}
					</Select.Trigger>
					<Select.Content>
						<Select.Group>
							<Select.Label>Severity</Select.Label>
							{#each severityOptions as option (option.value)}
								<Select.Item value={option.value} label={option.label}>
									{option.label}
								</Select.Item>
							{/each}
						</Select.Group>
					</Select.Content>
				</Select.Root>
			</div>

			<div class="flex items-center space-x-2">
				<SearchCode class="text-muted-foreground h-4 w-4" />
				<Select.Root type="single" value={selectedScanId} onValueChange={handleScanSelection}>
					<Select.Trigger class="w-[280px]">
						{selectedScanLabel}
					</Select.Trigger>
					<Select.Content>
						<Select.Group>
							<Select.Label>Scans</Select.Label>
							{#each scans as scan (scan.id)}
								<Select.Item value={scan.id} label={scan.id}>
									{scan.status === 'completed'
										? '✅'
										: scan.status === 'running'
											? '🔄'
											: scan.status === 'failed'
												? '❌'
												: '⏳'}
									{scan.finishedAt
										? new Date(scan.finishedAt).toLocaleDateString() +
											' ' +
											new Date(scan.finishedAt).toLocaleTimeString()
										: scan.startedAt
											? new Date(scan.startedAt).toLocaleDateString() +
												' ' +
												new Date(scan.startedAt).toLocaleTimeString()
											: 'Unknown'}
								</Select.Item>
							{/each}
						</Select.Group>
					</Select.Content>
				</Select.Root>
			</div>
		</div>

		<div class="flex-1 overflow-y-auto">
			{#if filteredIssues.length === 0}
				<div class="p-8 text-center">
					<CheckCircle class="mx-auto mb-4 h-12 w-12 text-green-500" />
					<p class="text-muted-foreground text-lg font-medium">No issues found</p>
					<p class="text-muted-foreground text-sm">
						{selectedSeverity === 'all'
							? 'Your code looks secure!'
							: `No ${selectedSeverity} severity issues found.`}
					</p>
				</div>
			{:else}
				<div class="space-y-3 p-4">
					{#each filteredIssues as issue (issue.id)}
						<button
							class="w-full cursor-pointer rounded-lg border p-4 text-left transition-all hover:shadow-md {issue.severity ===
							'CRITICAL'
								? 'border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-900/20'
								: issue.severity === 'HIGH'
									? 'border-orange-200 bg-orange-50 dark:border-orange-800 dark:bg-orange-900/20'
									: issue.severity === 'MEDIUM'
										? 'border-yellow-200 bg-yellow-50 dark:border-yellow-800 dark:bg-yellow-900/20'
										: 'border-blue-200 bg-blue-50 dark:border-blue-800 dark:bg-blue-900/20'}"
							onclick={() =>
								handleVulnerabilityClick({
									id: issue.id,
									description: issue.description,
									severity: issue.severity.toLowerCase() as Severity,
									filePath: issue.filePath,
									lines: issue.lines,
									recommendation: issue.recommendation,
									cwe: issue.cwe && issue.cwe !== 'null' ? issue.cwe : undefined,
									type: issue.type,
									scanId: selectedScanId,
									projectId: projectId || ''
								})}
						>
							<div class="flex items-start space-x-3">
								<div class="min-w-0 flex-1">
									<div class="flex items-start space-x-3">
										<div class="mt-0.5 h-5 w-5 flex-shrink-0">
											{#if issue.severity === 'CRITICAL'}
												<XCircle class="h-5 w-5 text-red-600" />
											{:else if issue.severity === 'HIGH'}
												<AlertCircle class="h-5 w-5 text-orange-600" />
											{:else if issue.severity === 'MEDIUM'}
												<AlertTriangle class="h-5 w-5 text-yellow-600" />
											{:else}
												<Info class="h-5 w-5 text-blue-600" />
											{/if}
										</div>
										<div class="min-w-0 flex-1">
											<div class="flex items-center justify-between">
												<h4 class="truncate text-sm font-medium">
													{issue.type}
												</h4>
											</div>
											<p class="text-muted-foreground mt-1 text-sm font-thin">
												{issue.description}
											</p>
											<div class="text-muted-foreground mt-2 flex items-center space-x-4 text-xs">
												<span class="truncate">{issue.filePath}</span>
												<span class="whitespace-nowrap">
													{issue.lines.length === 1 ? 'Line' : 'Lines'}{' '}
													{issue.lines.join(', ')}
												</span>
												{#if issue.cwe !== 'null'}
													<span>{issue.cwe}</span>
												{/if}
											</div>
										</div>
									</div>

									{#if expandedVuln === issue.id}
										<div class="mt-3 border-t border-gray-200 pt-3 dark:border-gray-600">
											<div class="space-y-2">
												<div>
													<h5 class="text-xs font-medium text-gray-900 dark:text-gray-100">
														Recommendation:
													</h5>
													<p class="text-xs text-gray-700 dark:text-gray-300">
														{issue.recommendation}
													</p>
												</div>
											</div>
										</div>
									{/if}
								</div>
							</div>
						</button>
					{/each}
				</div>
			{/if}
		</div>
	</div>
{/if}

// frontend/src/components/analysis-panel.tsx
import React, { useEffect, useState } from "react";
import {
  Info,
  CheckCircle,
  Clock,
  Filter,
  XCircle,
  AlertCircle,
  AlertTriangle,
  SearchCode,
} from "lucide-react";
import type { Vulnerability } from "@/types";
import type { Scans } from "@/services/api";
import StatCard from "./ui/stat-card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "./ui/select";

interface AnalysisPanelProps {
  onVulnerabilitySelect: (vulnerability: Vulnerability) => void;
  onScanChange?: (scanId: string | null) => void;
  scans: Scans[];
}

const AnalysisPanel: React.FC<AnalysisPanelProps> = ({
  onVulnerabilitySelect,
  onScanChange,
  scans,
}) => {
  const [selectedSeverity, setSelectedSeverity] = useState("all");
  const [expandedVuln, setExpandedVuln] = useState<string | null>(null);
  const [selectedScan, setSelectedScan] = useState<Scans | null>(null);

  useEffect(() => {
    console.log("Scans received:", scans);

    const latestCompletedScan = scans
      .filter((scan) => scan.status === "completed" && scan.finishedAt)
      .sort((a, b) => {
        const dateA = new Date(a.finishedAt!);
        const dateB = new Date(b.finishedAt!);
        return dateB.getTime() - dateA.getTime();
      })[0];

    setSelectedScan(latestCompletedScan || scans[0] || null);
    console.log("Selected scan:", latestCompletedScan || scans[0]);

    // Notify parent of the selected scan
    if (onScanChange) {
      onScanChange(latestCompletedScan?.id || scans[0]?.id || null);
    }
  }, [scans, onScanChange]);

  const handleVulnerabilityClick = (vuln: Vulnerability) => {
    onVulnerabilitySelect(vuln);
    setExpandedVuln(expandedVuln === vuln.id ? null : vuln.id);
  };

  console.log(scans);

  if (scans.length === 0) {
    return (
      <div className="h-full flex items-center justify-center text-foreground">
        <div className="text-center">
          <Clock className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
          <p className="text-lg font-medium">No analysis available</p>
          <p className="text-sm">
            Start a scan to see security analysis results here.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col">
      <div className="p-4 border-b border-gray-200 dark:border-gray-600 flex-shrink-0">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            Security Analysis
          </h3>
        </div>

        <div className="grid grid-cols-2 gap-3 mb-4">
          <StatCard
            title="Total Issues"
            value={selectedScan?.results?.totalIssues || 0}
          />
          <StatCard
            title="Scanned Files"
            value={selectedScan?.results?.scannedFiles || 0}
          />
        </div>

        <div className="grid grid-cols-4 gap-2 mb-4">
          {Object.entries({
            critical: {
              title: "Critical",
              count: selectedScan?.results?.issuesBySeverity?.critical || 0,
              color: "text-red-600",
            },
            high: {
              title: "High",
              count: selectedScan?.results?.issuesBySeverity?.high || 0,
              color: "text-orange-600",
            },
            medium: {
              title: "Medium",
              count: selectedScan?.results?.issuesBySeverity?.medium || 0,
              color: "text-yellow-600",
            },
            low: {
              title: "Low",
              count: selectedScan?.results?.issuesBySeverity?.low || 0,
              color: "text-blue-600",
            },
          }).map(([key, { count, color, title }]) => (
            <StatCard
              key={key}
              layout="vertical"
              title={title}
              value={count}
              valueColor={color}
              className="cursor-pointer hover:bg-card transition-colors"
              onClick={() => {
                setSelectedSeverity(key);
                setExpandedVuln(null);
              }}
            />
          ))}
        </div>

        <div className="flex items-center space-x-2 mb-2">
          <Filter className="w-4 h-4 text-muted-foreground" />
          <Select value={selectedSeverity} onValueChange={setSelectedSeverity}>
            <SelectTrigger>
              <SelectValue placeholder="Select severity" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem
                onClick={() => {
                  setSelectedSeverity("all");
                }}
                value="all"
              >
                All Severities
              </SelectItem>
              <SelectItem value="critical">Critical</SelectItem>
              <SelectItem value="high">High</SelectItem>
              <SelectItem value="medium">Medium</SelectItem>
              <SelectItem value="low">Low</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="flex items-center space-x-2">
          <SearchCode className="w-4 h-4 text-muted-foreground" />
          <Select
            value={selectedScan?.id || ""}
            onValueChange={(scanId) => {
              const scan = scans.find((s) => s.id === scanId);
              setSelectedScan(scan || null);

              // Notify parent of the selected scan
              if (onScanChange) {
                onScanChange(scanId);
              }
            }}
          >
            <SelectTrigger>
              <SelectValue placeholder="Select scan" />
            </SelectTrigger>
            <SelectContent>
              {scans.map((scan) => (
                <SelectItem key={scan.id} value={scan.id}>
                  <div className="flex items-center space-x-2">
                    <span>
                      {scan.status === "completed"
                        ? "✅"
                        : scan.status === "running"
                        ? "🔄"
                        : scan.status === "failed"
                        ? "❌"
                        : "⏳"}
                    </span>
                    <span>
                      {scan.finishedAt
                        ? new Date(scan.finishedAt).toLocaleDateString() +
                          " " +
                          new Date(scan.finishedAt).toLocaleTimeString()
                        : scan.startedAt
                        ? new Date(scan.startedAt).toLocaleDateString() +
                          " " +
                          new Date(scan.startedAt).toLocaleTimeString()
                        : "Unknown"}
                    </span>
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto">
        {selectedScan?.issues?.filter(
          (issue) =>
            selectedSeverity === "all" ||
            issue.severity.toLowerCase() === selectedSeverity
        ).length === 0 ? (
          <div className="p-8 text-center">
            <CheckCircle className="w-12 h-12 mx-auto mb-4 text-green-500" />
            <p className="text-lg font-medium text-muted-foreground">
              No issues found
            </p>
            <p className="text-sm text-muted-foreground">
              {selectedSeverity === "all"
                ? "Your code looks secure!"
                : `No ${selectedSeverity} severity issues found.`}
            </p>
          </div>
        ) : (
          <div className="p-4 space-y-3">
            {selectedScan?.issues
              ?.filter(
                (issue) =>
                  selectedSeverity === "all" ||
                  issue.severity.toLowerCase() === selectedSeverity
              )
              .map((issue) => (
                <div
                  key={issue.id}
                  className={`border rounded-lg p-4 cursor-pointer transition-all hover:shadow-md ${
                    issue.severity === "CRITICAL"
                      ? "border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-900/20"
                      : issue.severity === "HIGH"
                      ? "border-orange-200 bg-orange-50 dark:border-orange-800 dark:bg-orange-900/20"
                      : issue.severity === "MEDIUM"
                      ? "border-yellow-200 bg-yellow-50 dark:border-yellow-800 dark:bg-yellow-900/20"
                      : "border-blue-200 bg-blue-50 dark:border-blue-800 dark:bg-blue-900/20"
                  }`}
                  onClick={() =>
                    handleVulnerabilityClick({
                      id: issue.id,
                      title: issue.type,
                      description: issue.description,
                      type: issue.severity.toLowerCase() as
                        | "critical"
                        | "high"
                        | "medium"
                        | "low"
                        | "info",
                      file: issue.filePath,
                      line: issue.lines[0] || 0,
                      code: "",
                      recommendation: issue.recommendation,
                      cweId:
                        issue.cwe && issue.cwe !== "null"
                          ? issue.cwe
                          : undefined,
                    })
                  }
                >
                  <div className="flex items-start space-x-3">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start space-x-3">
                        <div className="w-5 h-5 mt-0.5 flex-shrink-0">
                          {issue.severity === "CRITICAL" ? (
                            <XCircle className="w-5 h-5 text-red-600" />
                          ) : issue.severity === "HIGH" ? (
                            <AlertCircle className="w-5 h-5 text-orange-600" />
                          ) : issue.severity === "MEDIUM" ? (
                            <AlertTriangle className="w-5 h-5 text-yellow-600" />
                          ) : (
                            <Info className="w-5 h-5 text-blue-600" />
                          )}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center justify-between">
                            <h4 className="text-sm font-medium truncate">
                              {issue.type}
                            </h4>
                          </div>
                          <p className="text-sm text-muted-foreground font-thin mt-1">
                            {issue.description}
                          </p>
                          <div className="mt-2 flex items-center text-xs text-muted-foreground space-x-4">
                            <span className="truncate">{issue.filePath}</span>
                            <span className="whitespace-nowrap">
                              {issue.lines.length === 1 ? "Line" : "Lines"}{" "}
                              {issue.lines.join(", ")}
                            </span>
                            {issue.cwe !== "null" && <span>{issue.cwe}</span>}
                          </div>
                        </div>
                      </div>

                      {expandedVuln === issue.id && (
                        <div className="mt-3 pt-3 border-t border-gray-200 dark:border-gray-600 ">
                          <div className="space-y-2">
                            <div>
                              <h5 className="text-xs font-medium text-gray-900 dark:text-gray-100">
                                Recommendation:
                              </h5>
                              <p className="text-xs text-gray-700 dark:text-gray-300">
                                {issue.recommendation}
                              </p>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default AnalysisPanel;
