// frontend/src/lib/components/layout/header.svelte
<script lang="ts">
	import { Shield, Zap, Sun, Moon } from 'lucide-svelte';
	import { Button } from '../ui/button/';
	import { toggleMode } from 'mode-watcher';
	import { page } from '$app/state';
	import type { NavigationItems } from '$lib/types/navigation';

	const navigationItems: NavigationItems = {
		dashboard: {
			label: 'Dashboard',
			path: '/'
		},
		projects: {
			label: 'Create Project',
			path: '/project/new'
		}
	};
</script>

<header class="bg-muted border-b px-6 py-4 shadow-sm">
	<div class="flex items-center justify-between">
		<a class="flex cursor-pointer items-center space-x-3" href="/">
			<div class="relative">
				<Shield class="h-8 w-8 text-blue-400" />
				<Zap class="absolute -top-1 -right-1 h-4 w-4 text-yellow-400" />
			</div>
			<div>
				<h1
					class="bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-xl font-bold text-transparent"
				>
					CodeGeist
				</h1>
				<p class="text-muted-foreground text-xs font-medium">Code Security Analysis</p>
			</div>
		</a>

		<nav class="flex items-center space-x-1">
			{#each Object.entries(navigationItems) as [_, { label, path }]}
				<Button
					class={page.url.pathname === path ? 'text-white' : ''}
					href={path}
					variant={page.url.pathname === path ? 'default' : 'ghost'}
				>
					{label}
				</Button>
			{/each}
		</nav>

		<div class="flex items-center space-x-3">
			<Button onclick={toggleMode} variant="ghost" size="icon">
				<Sun class="absolute hidden h-5 w-5 dark:block" />
				<Moon class="absolute block h-5 w-5 dark:hidden" />
				<span class="sr-only">Toggle theme</span>
			</Button>
		</div>
	</div>
</header>

// frontend/src/components/layout/header.tsx
import React from "react";
import { Shield, Settings, User, Zap } from "lucide-react";
import { useNavigate, useLocation } from "react-router-dom";
import { Button } from "@/components/ui/button";
import ThemeToggle from "@/components/ui/theme-toggle";

const Header: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const navigationItems = {
    dashboard: {
      label: "Dashboard",
      path: "/",
    },
    projects: {
      label: "Create Project",
      path: "/project/create",
    },
  };

  const getCurrentView = () => {
    if (location.pathname.startsWith("/project/create")) return "projects";
    return "dashboard";
  };

  const currentView = getCurrentView();

  return (
    <header className="bg-background px-6 py-4 shadow-sm border-b">
      <div className="flex items-center justify-between">
        <div
          className="flex items-center space-x-3 cursor-pointer"
          onClick={() => navigate("/")}
        >
          <div className="relative">
            <Shield className="w-8 h-8 " />
            <Zap className="w-4 h-4 absolute -top-0.5 -right-0.5 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-bold bg-clip-text ">CodeGeist</h1>
            <p className="text-xs text-slate-500 font-medium">
              Code Security Analysis
            </p>
          </div>
        </div>

        <nav className="flex items-center space-x-1">
          {Object.entries(navigationItems).map(([key, { label, path }]) => (
            <Button
              key={key}
              variant={currentView === key ? "secondary" : "ghost"}
              onClick={() => navigate(path)}
            >
              {label}
            </Button>
          ))}
        </nav>

        <div className="flex items-center space-x-3">
          <ThemeToggle />
          <Button variant="ghost" size="icon">
            <Settings className="w-5 h-5" />
          </Button>
          <Button variant="ghost" size="icon">
            <User className="w-5 h-5" />
          </Button>
        </div>
      </div>
    </header>
  );
};

export default Header;
