// frontend-v2/src/lib/components/layout/project-header.svelte
<script lang="ts">
	import type { Project } from '$lib/types/api';
	import { Button } from '$lib/components/ui/button';
	import { Skeleton } from '$lib/components/ui/skeleton';
	import { Radar } from 'lucide-svelte';

	export let project: Project;
	export let isLoading: boolean = false;

	const startScanHandler = () => {
		console.log('Starting scan for project:', project.id);
	};
</script>

<section class="border-b px-6 py-4">
	<div class="flex items-center justify-between">
		{#if isLoading}
			<div>
				<Skeleton class="mb-1 h-7 w-64" />
				<Skeleton class="mb-1 h-5 w-80" />
			</div>

			<Skeleton class="h-10 w-24 rounded" />
		{:else}
			<div>
				<h2 class="text-xl font-semibold">{project.name}</h2>

				<p class="text-muted-foreground text-sm">
					{project.totalFiles ?? 0} files · {project.totalSize} · Uploaded&nbsp;at&nbsp;
					{project.updatedAt}
				</p>
				{#if project.url}
					<a
						href={project.url}
						target="_blank"
						rel="noreferrer"
						class="text-primary text-xs hover:underline"
					>
						{project.url.replace(/^https?:\/\//, '')}
					</a>
				{/if}
			</div>

			<Button onclick={startScanHandler} size="lg" class="font-semibold text-white">
				<Radar class="mr-1 h-4 w-4 " />
				Start Analysis
			</Button>
		{/if}
	</div>
</section>

// frontend/src/components/layout/project-header.tsx
import type { Project } from "@/services/api";
import { format } from "date-fns";
import { Button } from "../ui/button";
import { Radar } from "lucide-react";

interface ProjectHeaderProps {
  project: Project;
}

const kb = (bytes: number | undefined) =>
  bytes ? `${Math.round(bytes / 1024)} KB` : "0 KB";

const ProjectHeader: React.FC<ProjectHeaderProps> = ({ project }) => {
  const uploadedAt = new Date(project.createdAt ?? 0);

  return (
    <header className="border-b px-6 py-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold ">{project.name}</h2>

          <p className="text-sm text-muted-foreground">
            {project.totalFiles ?? 0} files · {kb(project.totalSize)} ·
            Uploaded&nbsp;at&nbsp;
            {format(uploadedAt, "dd/MM/yyyy HH:mm")}
          </p>

          {project.url && (
            <a
              href={project.url}
              target="_blank"
              rel="noreferrer"
              className="text-xs text-primary hover:underline"
            >
              {project.url.replace(/^https?:\/\//, "")}
            </a>
          )}
        </div>

        <Button size="lg" className="text-white font-semibold">
          <Radar className="w-4 h-4 mr-1 " />
          Analyze
        </Button>
      </div>
    </header>
  );
};
export default ProjectHeader;
