// frontend/src/components/layout/layout.tsx
import React from "react";
import type { ReactNode } from "react";
import Header from "./header";

interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const currentPath = window.location.pathname;

  if (currentPath.startsWith("/projects/")) {
    return (
      <div className="h-screen flex flex-col overflow-hidden">
        <Header />
        <div className="flex-1 overflow-hidden">{children}</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col overflow-y-auto">
      <Header />
      <div className="flex-1">{children}</div>
    </div>
  );
};

export default Layout;

// frontend-v2/src/lib/components/layout/layout.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { Header } from './';

	let { children } = $props();

	console.log('Page URL:', page.url.pathname);
</script>

{#if page.url.pathname.startsWith('/project/') && page.url.pathname !== '/project/new'}
	<div class="flex h-screen flex-col overflow-hidden">
		<Header />
		<div class="flex-1 overflow-hidden">{@render children()}</div>
	</div>
{:else}
	<div class="flex min-h-screen flex-col overflow-y-auto">
		<Header />
		<div class="flex-1 overflow-hidden">
			{@render children()}
		</div>
	</div>
{/if}
